#!/usr/bin/env python3
"""Embed src/web/ files into tree.cpp as a compiled-in fallback."""
import os, sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR)
WEB_DIR = os.path.join(PROJECT_DIR, "src", "web")
SRC_CPP = os.path.join(PROJECT_DIR, "src", "tree.cpp")
OUT_H = os.path.join(PROJECT_DIR, "src", "web_embed.h")

def read_file(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()

def build_inline_html():
    index = read_file(os.path.join(WEB_DIR, "index.html"))
    css = read_file(os.path.join(WEB_DIR, "styles.css"))
    app_js = read_file(os.path.join(WEB_DIR, "app.js"))
    i18n_js = read_file(os.path.join(WEB_DIR, "i18n.js"))
    webgl_js = read_file(os.path.join(WEB_DIR, "webgl.js"))

    css_tag = f"<style>\n{css}\n</style>\n"
    head_close = index.find("</head>")
    if head_close != -1:
        index = index[:head_close] + css_tag + index[head_close:]

    js_blocks = f"<script>\n{i18n_js}\n</script>\n<script>\n{app_js}\n</script>\n<script>\n{webgl_js}\n</script>\n"
    body_close = index.find("</body>")
    if body_close != -1:
        index = index[:body_close] + js_blocks + index[body_close:]

    index = index.replace('<link rel="stylesheet" href="/styles.css">', "")
    index = index.replace('<script src="/i18n.js"></script>', "")
    index = index.replace('<script src="/app.js"></script>', "")
    index = index.replace('<script src="/webgl.js"></script>', "")

    return index

def generate_header(html):
    chunk_size = 15000
    header = "// Auto-generated by scripts/embed-web.py -- do not edit\n"
    if len(html) <= chunk_size:
        header += f'    return R"html({html})html";'
    else:
        header += "    return"
        for i in range(0, len(html), chunk_size):
            chunk = html[i:i + chunk_size]
            header += f'\n           R"html({chunk})html"'
        header += ";"
    return header

def main():
    if not os.path.isdir(WEB_DIR):
        print("[embed-web] ERROR: src/web/ not found", file=sys.stderr)
        sys.exit(1)

    html = build_inline_html()
    header = generate_header(html)

    with open(OUT_H, "w", encoding="utf-8") as f:
        f.write(header)

    print(f"[embed-web] Generated {OUT_H} ({len(html)} bytes)")

if __name__ == "__main__":
    main()
